import '../../../llm/chat_templates.dart';
import '../../../llm/model_descriptor.dart';
import '../domain/llm_errors.dart';
import '../domain/llm_service.dart';
import '../domain/message.dart';
import '../domain/message_role.dart';
import '../domain/prompt.dart';
import '../domain/tokenizer.dart';

/// Folds turns that fell out of the context window into a rolling summary
/// (technical-spec §5.2.3).
///
/// "Generated by the same model, capped at a fixed token length", per §5.2.3.
/// The cap is the load-bearing part: an uncapped summary would grow with the
/// conversation and eventually consume the budget it exists to protect, which is
/// exactly the cost it was introduced to bound.
///
/// The summary is persisted on the conversation, so reopening an old
/// conversation stays within §8's prefill ceiling instead of regenerating it
/// every time.
class ConversationSummariser {
  const ConversationSummariser({
    required this.tokenizer,
    this.maxTokens = 256,
  });

  final Tokenizer tokenizer;

  /// The cap. Deliberately small relative to any model's window.
  final int maxTokens;

  /// Rewrites [previousSummary] to also cover [folded].
  ///
  /// Returns `null` when there is nothing to do, or when the model produced
  /// nothing usable — a failed summarisation must not take the turn down with
  /// it, because the user's conversation continues either way. The cost of
  /// returning null is that the same turns are offered again next time.
  Future<String?> summarise({
    required LlmService llm,
    required ModelDescriptor model,
    required List<Message> folded,
    String? previousSummary,
  }) async {
    if (folded.isEmpty) return null;

    final template = ChatTemplate.forFamily(model.family);
    final prompt = _instruction(template, model, folded, previousSummary);

    LlmSession? session;
    try {
      // A session of its own, disposed immediately. Sending this through the
      // conversation's live session would poison the KV cache the session exists
      // to keep: the summarisation instruction and its output would become part
      // of the conversation the model believes it is having.
      session = await llm.openSession(seed: prompt);
      final buffer = StringBuffer();
      await for (final token in session.send(prompt)) {
        buffer.write(token);
      }
      final summary = buffer.toString().trim();
      return summary.isEmpty ? null : _cap(summary);
    } on LlmException {
      return null;
    } finally {
      await session?.dispose();
    }
  }

  Prompt _instruction(
    ChatTemplate template,
    ModelDescriptor model,
    List<Message> folded,
    String? previousSummary,
  ) {
    final transcript = folded
        .map((m) => '${m.role == MessageRole.user ? 'Person' : 'LEV'}: '
            '${m.text}')
        .join('\n');

    final task = StringBuffer()
      ..writeln(
        'Condense the exchange below into a short third-person note that '
        'preserves what the person is dealing with, what matters to them, and '
        'anything already agreed or tried. Keep it factual and neutral. Do not '
        'add advice, comfort or interpretation. Write no more than a short '
        'paragraph.',
      );

    if (previousSummary != null && previousSummary.trim().isNotEmpty) {
      task
        ..writeln()
        ..writeln('Existing note, which the new one must absorb and replace:')
        ..writeln(previousSummary.trim());
    }

    task
      ..writeln()
      ..writeln('Exchange:')
      ..writeln(transcript);

    final text = template.preamble +
        template.turn(MessageRole.user, task.toString().trim()) +
        template.assistantCue;

    return Prompt(
      text: text,
      stopTokens: model.stopTokens,
      estimatedTokens: tokenizer.count(text),
    );
  }

  /// Enforces the cap by trimming whole sentences off the end.
  ///
  /// Sentences rather than tokens: a summary cut mid-clause reads as though the
  /// conversation itself was cut off there, and the model is being asked to
  /// treat it as fact.
  String _cap(String summary) {
    if (tokenizer.count(summary) <= maxTokens) return summary;

    final sentences = summary.split(RegExp(r'(?<=[.!?])\s+'));
    final kept = StringBuffer();
    for (final sentence in sentences) {
      final candidate =
          kept.isEmpty ? sentence : '${kept.toString()} $sentence';
      if (tokenizer.count(candidate) > maxTokens) break;
      kept
        ..clear()
        ..write(candidate);
    }

    // A single sentence longer than the whole cap: keep a hard-trimmed prefix
    // rather than nothing, since nothing would drop the folded turns entirely.
    if (kept.isEmpty) {
      final words = summary.split(RegExp(r'\s+'));
      final trimmed = StringBuffer();
      for (final word in words) {
        final candidate =
            trimmed.isEmpty ? word : '${trimmed.toString()} $word';
        if (tokenizer.count(candidate) > maxTokens) break;
        trimmed
          ..clear()
          ..write(candidate);
      }
      return trimmed.isEmpty ? '' : '${trimmed.toString()}…';
    }

    return kept.toString();
  }
}
